Editor:
  LastProjectPath: D:\gitnext\Chained Decos\game\chaineddecos\ChainedDecos.chproject
  LastScenePath: D:\gitnext\Chained Decos\game\chaineddecos\assets\scenes\untitled100.chscene
  LoadLastProjectOnStartup: false